name: Run advent of code

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm i
      - run: DAY=day1 npm run day
        continue-on-error: true
      - run: DAY=day2 npm run day
        continue-on-error: true
      - run: DAY=day3 npm run day
        continue-on-error: true
      - run: DAY=day4 npm run day
        continue-on-error: true
      - run: DAY=day5 npm run day
        continue-on-error: true
      - run: DAY=day6 npm run day
        continue-on-error: true
      - run: DAY=day7 npm run day
        continue-on-error: true
      - run: DAY=day8 npm run day
        continue-on-error: true
      - run: DAY=day9 npm run day
        continue-on-error: true
      - run: DAY=day10 npm run day
        continue-on-error: true
      - run: DAY=day11 npm run day
        continue-on-error: true
      - run: DAY=day12 npm run day
        continue-on-error: true
      - run: DAY=day13 npm run day
        continue-on-error: true
